module.exports = [
  {
    commonName: 'Palm tree',
    family: 'perennial plants',
    careDifficulty: 3,
    watering: 'weekly',
    lifeLength: 'more than 10 years',
    img: '/images/livistona_palm.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Avocado',
    family: 'Lauraceae',
    careDifficulty: 3,
    watering: 'weekly',
    lifeLength: 'some months',
    img: '/images/avocado.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Lavender',
    family: 'Lamiaceae',
    careDifficulty: 3,
    watering: 'twice a week',
    lifeLength: 'some months',
    img: '/images/lavender.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Cactus',
    family: 'Cactaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'some months',
    img: '/images/cactus_succulent.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Lemon',
    family: 'Rutaceae',
    careDifficulty: 3,
    watering: 'weekly',
    lifeLength: 'some months',
    img: '/images/lemon.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Aloe vera',
    family: 'Asphodelaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'many years',
    img: '/images/aloe_vera.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Lupin',
    family: 'Fabaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'many years',
    img: '/images/lupin.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Papaver',
    family: 'Papaveraceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'many years',
    img: '/images/papaver.jpg',
    careTips: ['lorem ipsum'],
    place: ['indoor', 'office', 'living room'],
    description: 'lorem ipsum',
  },
  {
    commonName: 'Flamingo Flower',
    family: 'araceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'many years',
    img: '/images/anthurium.jpg',
    careTips: [
      'planted with acidic soil, temperatures of 60 °F to 90 °F, fertilize every month through the growing season, water thoroughly',
    ],
    place: ['Indoor'],
    description:
      'Common houseplant Anthuriums are grown for their brightly colored flower spathes and their ornamental leaves. They need bright but indirect light.',
  },
  {
    commonName: 'Bamboo',
    family: 'Poaceae',
    careDifficulty: 3,
    watering: 'every 5-10 days',
    lifeLength: '1-2 years',
    img: '/images/bamboo.jpg',
    careTips: [
      'Keep the bamboo palm moist, but never overwater',
      'water sparingly, should be kept in a transparent container so that you can see its roots',
    ],
    place: ['indoor', 'office', 'kitchen', 'living room'],
    description:
      'Bamboo grows differently than most other plants. It is difficult to grasp what is happening. It did not get the title of “fastest growing woody plant on earth!',
  },
  {
    common_name: 'Snake',
    family: 'Asparagaceae',
    careDifficulty: 1,
    watering: 'twice a month',
    lifeLength: 'many years',
    img: '/images/snake_plant.jpg',
    careTips: ['bright indirect light is best for this plant'],
    place: ['indoor', 'office', 'living room'],
    description:
      "it is a stemless evergreen perennial. In its native habitat, plant foliage may rise to as much as 4' tall, but is often smaller (to 2' tall) on indoor plants. Erect, fleshy, sharply-pointed, sword-shaped leaves are deep green with light gray-green horizontal stripes.",
  },
  {
    common_name: 'Jade',
    family: 'Crassulaceae',
    careDifficulty: 1,
    watering: 'once every 2 or 3 weeks',
    lifeLength: 'many years',
    img: '/images/jade.jpg',
    careTips: [
      'keep them outside for the summer before bringing them in',
      'perfect location is right beside a window',
    ],
    place: ['Indoor', 'outdoor', 'dining room'],
    description:
      'Crassula ovata is a succulent plant with small pink or white flowers that is native to the KwaZulu-Natal province and Eastern Cape of South Africa and Mozambique, and is common as a houseplant worldwide. Jade Plant is also a popular good luck charm in Asia thought to activate financial energies.',
  },
  {
    commonName: 'Pothos',
    family: 'Araceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: '5 to 10 years',
    img: '/images/pothos.jpg',
    careTips: [
      'pay a little attention to its leaves to decide when to water it, not direct light',
    ],
    place: ['indoor', 'bedroom', 'office'],
    description:
      'Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. It is commonly grown as a hanging plant.',
  },
  {
    commonName: 'Ficus Benjamina',
    family: 'Moraceae',
    careDifficulty: 2,
    watering: 'every 5-10 days',
    lifeLength: '10 years',
    img: '/images/ficus_benjamina.jpg',
    careTips: [
      'the more colorful the leaves',
      'the sunnier the location should be, shade from strong midday sun is absolutely necessary',
    ],
    place: ['indoor', 'office', 'living room', 'balcony'],
    description: [
      'Ficus benjamina is actually a real tree, with its hard trunk crowned with branches full of green leaves.',
    ],
  },
  {
    commonName: 'Yucca',
    family: 'Asparagaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: '5-7 years',
    img: '/images/yucca.jpg',
    careTips: [
      'they all do better with ample sun',
      'will do best in an east west or south-facing window',
      'take care of the pointy leaf tips',
    ],
    place: ['indoors'],
    description:
      'The Yucca plant is a widely popular drought tolerant evergreen garden perennial that grow either as shrubs or small trees, requiring minimum care.',
  },
  {
    commonName: 'Orchid',
    family: 'String',
    careDifficulty: 3,
    watering: 'every 5-10 days',
    lifeLength: '2 to 3 months',
    img: '/images/orchid.jpg',
    careTips: [
      'Always water early in the day',
      'ensure the plant is not constantly sitting in water so that it causes the roots to rot',
      'Use pots with drainage holes, indirect sun location',
    ],
    place: ['indoor', 'office', 'living room', 'gift'],
    description:
      'The Orchidaceae are a diverse and widespread family of flowering plants, with blooms that are often colourful and fragrant, commonly known as the orchid.',
  },
  {
    commonName: 'Eucalyptus',
    family: 'Myrtaceae',
    careDifficulty: 3,
    watering: 'Weekly',
    lifeLength: 'Many years potted, trees around 250 years',
    img: '/images/eucalyptus.jpg',
    careTips: [
      'sunny location',
      'place the peat pots in a warm area and mist them frequently to keep the soil evenly moist',
    ],
    place: ['Yard', 'balcony'],
    description:
      'Eucalyptus is a type of tree that’s native to Australia, but that can grow anywhere that the temperatures don’t drop below 10 °F (−12 °C). There are actually many different species of eucalyptus, but they all have silvery leaves that are very aromatic, making them popular in floral arrangements.',
  },
];
