module.exports = [
  {
    commonName: 'African violet',
    family: 'Gesneriaceae',
    careDifficulty: 2,
    watering: '10-15 days',
    lifeLength: 'More than 10 years',
    img: '/images/plant-africanviolet.jpg',
    careTips: [
      'Keep them planted in small pots and re-pot once a year to mix in fresh soil.',
      'Dust dirt off the leaves with a small, soft brush.',
      'Fertilize every 2 weeks with a high phosphorous plant food, but only during the spring and summer growing season.',
    ],
    place: ['kitchen', 'living room', 'terrace'],
    description: 'Small houseplants that produce clusters of white, blue, or purple flowers over fuzzy leaves. \n African violets originally come from Tanzania. The violet symbolizes loyalty, devotion, and faithfulness.',
  },
  {
    commonName: 'Aloe vera',
    family: 'Asphodelaceae',
    careDifficulty: 1,
    watering: '10-15 days',
    lifeLength: '5-25 years',
    img: '/images/plant-aloevera.jpg',
    careTips: [
      'Needs bright and indirect light',
      'Water when the soil is completely dry.',
      'Place your Aloe Vera near a window where you have bright light all day long.',
      'Fertilize sparingly (no more than once a month)',
    ],
    place: ['bedroom', 'office', 'living room', 'kitchen', 'terrace', 'bathroom'],
    description: 'It\'s a succulent plant species of the genus Aloe. An evergreen perennial, it originates from the Arabian Peninsula but grows wild in tropical climates around the world and is cultivated for agricultural and medicinal uses. \n The species is also used for decorative purposes and grows successfully indoors as a potted plant. \n t is found in many consumer products including beverages, skin lotion, cosmetics, or ointments for minor burns and sunburns. There is little clinical evidence for the effectiveness or safety of Aloe vera extract as a cosmetic or medicine.',
  },
  {
    commonName: 'Avocado tree',
    family: 'Lauraceae',
    careDifficulty: 2,
    watering: 'twice a week',
    lifeLength: 'more than 10 years',
    img: '/images/plant-avocado.jpg',
    careTips: [
      'Keep the plant soil consistently moist but not over watered.',
      'Fertilize the plant every three months with a small amount of water-soluble food to facilitate growth and healthy deep green foliage.',
      'You can move the avocado houseplant outdoors to a partially shaded area when the weather warms.',
    ],
    place: ['kitchen', 'terrace', 'living room'],
    description: 'Avocado trees most likly originated in Southern Mexico and were cultivated for centuries before North America was colonized. The pear-shaped fruits are a delicious, rich food that make an excellent condiment or eat alone addition to your diet. \n The trees are warm season plants, easily damaged by cold and frost. \n Do not expect fruit when growing avocados in containers. Indoor plants need cool nights to force blooming and fruiting.',
  },
  {
    commonName: 'Bamboo',
    family: 'Poaceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: 'more than 10 years',
    img: '/images/plant-bamboo.jpg',
    careTips: [
      'Keep the bamboo palm moist, but never overwater',
      'Water sparingly, should be kept in a transparent container so that you can see its roots',
      'In full sun it will grow the fastest',
    ],
    place: ['bathroom', 'office', 'kitchen', 'living room'],
    description:
      'Bamboo grows differently than most other plants. It\'s difficult to grasp what is happening. It did not get the title of “fastest growing woody plant on earth!',
  },
  {
    commonName: 'Basil',
    family: 'Lamiaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: '4-6 months',
    img: '/images/plant-basil.jpg',
    careTips: [
      'Don’t rush basil. Without heat, the plant won’t grow well.',
      'Soil should be moist but well-drained.',
      'It works great in containers or raised beds, as these allow for better drainage.',
    ],
    place: ['terrace', 'kitchen'],
    description:
      'Basil plants are one of the most popular herbs to grow and also one of the easiest. \n It is closely identified with Italian cooking, although it is originally from India. The extremely aromatic leaves also have a delightful variety of flavors, from the slightly lemony-mint of sweet basil to cinnamon, and licorice.',
  },
  {
    commonName: 'Dracaena',
    family: 'Asparagaceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: 'more than 20 years',
    img: '/images/plant-dracaena.jpg',
    careTips: [
      'Filtered indoor light or a semi-shade spot is an ideal location.',
      'Keep them hydrated by misting the leaves with water and keeping the soil lightly misted (never soggy) as well with good drainage.',
      'The perfect pot is one with drain holes, in standard well-draining potting mix.',
    ],
    place: ['living room', 'office'],
    description:
      'A popular houseplant with origins in Madagascar and other Indian ocean islands. Dracaena plant care is fairly simple, and they can even withstand a certain amount of neglect. Best of all, dracaena help purify the air we breathe.',
  },
  {
    commonName: 'Eucalyptus',
    family: 'Myrtaceae',
    careDifficulty: 3,
    watering: 'weekly',
    lifeLength: 'more than 20 years',
    img: '/images/plant-eucalyptus.jpg',
    careTips: [
      'Note that eucalyptus is considered a heavy feeder and requires full sun.',
      'Place the peat pots in a warm area and mist them frequently to keep the soil evenly moist.',
      'Plant your tree in a large, cone-shaped Air-pot.',
    ],
    place: ['terrace'],
    description:
      'Eucalyptus is a type of tree that’s native to Australia, but that can grow anywhere that the temperatures don’t drop below 10 °F (−12 °C). \n There are actually many different species of eucalyptus, but they all have silvery leaves that are very aromatic, making them popular in floral arrangements.',
  },
  {
    commonName: 'Flamingo Flower',
    family: 'Araceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: '5-10 years',
    img: '/images/plant-flamingoflower.jpg',
    careTips: [
      'Planted with acidic soil.',
      'Temperatures of 60 °F to 90 °F.',
      'Fertilize every month through the growing season',
      'Water thoroughly',
    ],
    place: ['living room', 'office'],
    description:
      'With glossy green leaves and rich red blooms, Anthurium is one of the most stunning plants to grow indoors. \n Also known as flamingo flower or painter’s palette, it will add a touch of luxury to an indoor space. They need bright but indirect light.',
  },
  {
    commonName: 'Ficus Benjamina',
    family: 'Moraceae',
    careDifficulty: 2,
    watering: '5-10 days',
    lifeLength: 'more than 10 years',
    img: '/images/plant-ficusbenjamina.jpg',
    careTips: [
      'The more colorful the leaves, the sunnier the location should be.',
      'Shade from strong midday sun is absolutely necessary.',
      'It needs his soil to be moist most of the time for him to thrive.',
    ],
    place: ['office', 'living room'],
    description:
      'Ficus benjamina is actually a real tree, with its hard trunk crowned with branches full of green leaves. \n Well-known as the Weeping Fig, is a very popular house plant. Although he doesn\'t produce any flowers, his overall presence and elegance makes him a firm favourite',
  },
  {
    commonName: 'Jade',
    family: 'Crassulaceae',
    careDifficulty: 1,
    watering: '10-15 days',
    lifeLength: 'more than 20 years',
    img: '/images/plant-jade.jpg',
    careTips: [
      'Keep them outside for the summer before bringing them in.',
      'Perfect location is right beside a window.',
      'Fertilize it about once every six months.',
    ],
    place: ['office', 'living room'],
    description:
      'Crassula ovata is a succulent plant with small pink or white flowers that is native to the KwaZulu-Natal province and Eastern Cape of South Africa and Mozambique, and is common as a houseplant worldwide. \n Jade Plant is also a popular good luck charm in Asia thought to activate financial energies.',
  },
  {
    commonName: 'Lavender',
    family: 'Lamiaceae',
    careDifficulty: 3,
    watering: 'twice a week',
    lifeLength: 'more than 10 years',
    img: '/images/plant-lavender.jpg',
    careTips: [
      'Keep away from wet, moist areas.',
      'Rotate the pot weekly for uniform growth and flowering.',
      'Cutting branches for flower harvest causes new growth to sprout and promotes bushiness.',
      'It requires at least 6 hours of sunshine per day. Shade reduces growth and fragance.',
    ],
    place: ['kitchen', 'bedroom', 'living room', 'terrace'],
    description: 'Lavender plants are small, branching and spreading shrubs with grey-green leaves and long flowering shoots. \n Prized for its fragrance, medicinal properties, and beautiful color, lavender is a valued plant across the world. \n It also attracts pollinators to the garden.',
  },
  {
    commonName: 'Lemon tree',
    family: 'Rutaceae',
    careDifficulty: 2,
    watering: '5-10 days',
    lifeLength: '2-5 years',
    img: '/images/plant-lemon.jpg',
    careTips: [
      'Choose a pot that is 25% bigger than the root ball of the plant.',
      'Repot your lemon tree in every couple of years or so at the beginning of spring.',
      'All plants in the citrus family love full sun, around 7 to 8 hours of sunlight is essential.',
    ],
    place: ['kitchen', 'office', 'living room'],
    description: 'This is known for its fragrant flowers and medium-sized, yellow fruit.  It produces a fruit that is tangy, juicy, and slightly sweet. \n In addition, this is a self-pollinating tree meaning you only need one. You won’t have to worry about having to pollinate it with your hands or a machine! \n However, a lemon tree doesn’t grow too big, which means you can grow almost any variety in the pot.',
  },
  {
    commonName: 'Livistona Palm tree',
    family: 'Araceae',
    careDifficulty: 3,
    watering: 'twice a week',
    lifeLength: 'more than 10 years',
    img: '/images/plant-palmtree.jpg',
    careTips: [
      'Doesn\'t like the direct sunlight',
      'Repot every year',
      'In summer spray and wipe regularly the leaves with a damp sponge.',
    ],
    place: ['terrace', 'office', 'living room'],
    description: 'Livistona is not the largest indoor palm but is the most elegant, with leaves that form almost a perfect circle. It grows from 60cm to 2m in a pot. \n It\'s a member of the palm family and grows in the tropical and subtropical rainforests of South-East Asia, Australia and the Horn of Africa. \n Livistona removes harmful substancesfrom the air around it and thereby helps to prevent irritated eyes, headache and fatigue, amongst other things. The houseplant also has a positive effect on humidity.',
  },
  {
    commonName: 'Lupin',
    family: 'Fabaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'more than 10 years',
    img: '/images/plant-lupin.jpg',
    careTips: [
      'Well draining soil',
      'Full sun is preferred. Lupine can grow in part shade, but flowering will be lessened.',
      'Lupines do not require fertilizer.',
    ],
    place: ['terrace'],
    description: 'Lupines are an ideal flower for beginners, requiring less than an hour of care per growing month. \n Their telltale look is a tall, showy spire of flowers that can come in a multitude of color varieties with impressive grayish-green textured foliage.',
  },
  {
    commonName: 'Mint',
    family: 'Lamiaceae',
    careDifficulty: 1,
    watering: 'daily',
    lifeLength: '2 months',
    img: '/images/plant-mint.jpg',
    careTips: [
      'It prefers partial shade.',
      'Choose a spot with moist but well drained soil.',
      'Place it next to a window.',
    ],
    place: ['terrace', 'kitchen'],
    description: 'All types of mint (including sweet mint, spearmint, peppermint, and chocolate mint) are fast-growing, spreading plants, so you must give them a place to spread without getting in the way, or plant them in a pot. \n Mint sends out runners that spread above and just below the ground, quickly forming large, lush green patches. In the right place it makes a pretty seasonal ground cover. \n You can also contain mint in tight places such as between pavers of a walkway where your feet will brush against the leaves to release its fragrance.',
  },
  {
    commonName: 'Orchid',
    family: 'Asparagaceae',
    careDifficulty: 3,
    watering: '5-10 days',
    lifeLength: '2-3 months',
    img: '/images/plant-orchid.jpg',
    careTips: [
      'Always water early in the day',
      'Ensure the plant is not constantly sitting in water so that it causes the roots to rot.',
      'Use pots with drainage holes, indirect sun location.',
    ],
    place: ['bathroom', 'kitchen', 'office'],
    description:
      'The Orchidaceae are a diverse and widespread family of flowering plants, with blooms that are often colourful and fragrant, commonly known as the orchid. \n The beauty, complexity and incredible diversity of orchid flowers are unrivalled in the plant world.',
  },
  {
    commonName: 'Peace Lily',
    family: 'Araceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: '3-5 years',
    img: '/images/plant-peacelily.jpg',
    careTips: [
      'Try to avoid exposing your plant to cold air or too much sun.',
      'Mist the leaves several times a week with a spray bottle.',
      'Trim any unhealthy leaves from your plant. ',
    ],
    place: ['living room', 'bathroom', 'bedroom', 'office'],
    description: 'Native primarily to tropical rainforests of America, the peace lily plant is a vibrant and graceful perennial that adds life to any space. \n These lovely plants not only brighten up a living space, but are also excellent at cleaning the air of the room they are in. \n Most commonly, these plants have dark green leaves and white “flowers.”',
  },
  {
    commonName: 'Poppy',
    family: 'Papaveraceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: '4 months',
    img: '/images/plant-papaver.jpg',
    careTips: [
      'Poppies will grow well in either a sunny or partially shaded position.',
      'After flowering, cut down the flowering stems and remove any old or damaged foliage to keep the plants looking good and tidy.',
      'Poppies don\'t require fertilization and rarely require watering except during dry weather.',
    ],
    place: ['terrace'],
    description: 'It comes from the Poppy family and it\'s is a flowering plant, often grown for their colourful flowers. \n The flowers of most poppy species are attractive and are widely cultivated as annual or perennial ornamental plants. A few species have other uses, principally as sources of drugs and foods.',
  },
  {
    commonName: 'Pothos',
    family: 'Araceae',
    careDifficulty: 2,
    watering: 'weekly',
    lifeLength: '5-10 years',
    img: '/images/plant-pothos.jpg',
    careTips: [
      'Pay a little attention to its leaves to decide when to water it, not direct light.',
      'It likes to have its soil dry out between waterings.',
      'Grow in any well-draining potting soil.',
    ],
    place: ['bathroom', 'bedroom', 'office', 'living room', 'kitchen'],
    description:
      'The pothos plant is considered by many to be a great way to get started caring for houseplants. \n Pothos is an evergreen plant with thick, waxy, green, heart-shaped leaves with splashes of yellow. It is commonly grown as a hanging plant.',
  },
  {
    commonName: 'Snake',
    family: 'Asparagaceae',
    careDifficulty: 1,
    watering: '10-15 days',
    lifeLength: '5-10 years',
    img: '/images/plant-snake.jpg',
    careTips: [
      'Bright indirect light is best for this plant.',
      'Let the soil dry between waterings.',
      'Wipe leaves with a damp cloth as needed to remove dust.',
    ],
    place: ['bathroom', 'office', 'living room', 'bedroom'],
    description:
      "Snake plants, also known as Mother-in-Law’s Tongue and Sansevieria, are one of the easiest house plants to take care of. This succulent plant is very forgiving and perfect for beginners. \n It is a stemless evergreen perennial. In its native habitat, plant foliage may rise to as much as 4' tall, but is often smaller (to 2' tall) on indoor plants. Erect, fleshy, sharply-pointed, sword-shaped leaves are deep green with light gray-green horizontal stripes.",
  },
  {
    commonName: 'Succulent',
    family: 'Cactaceae',
    careDifficulty: 1,
    watering: '10-15 days',
    lifeLength: '2-5 years',
    img: '/images/plant-cactus.jpg',
    careTips: [
      'Water more, but less often. The thicker the leaves on a succulent the less water it needs.',
      'Succulents need a lot of sunlight to grow happy and healthy. Place near windows.',
      'Rotate succulents frequently',
      'Use draining soil',
    ],
    place: ['bedroom', 'office', 'living room'],
    description: 'Succulent is a plant with parts that are thickened, fleshy and engorged, usually to retain water in arid climates or soil conditions. \n The word "succulent" comes from the Latin word sucus, meaning juice, or sap.',
  },
  {
    commonName: 'Yucca',
    family: 'Asparagaceae',
    careDifficulty: 1,
    watering: 'weekly',
    lifeLength: 'more than 10 years',
    img: '/images/plant-yucca.jpg',
    careTips: [
      'They all do better with ample sun.',
      'Will do best in an east west or south-facing window.',
      'Take care of the pointy leaf tips.',
    ],
    place: ['living room', 'office'],
    description:
      'The Yucca plant is a widely popular drought tolerant evergreen garden perennial that grow either as shrubs or small trees, requiring minimum care. \n Yuccas are widely grown as ornamental plants in gardens. Many species also bear edible parts, including fruits, seeds, flowers, flowering stems,[10] and more rarely roots.',
  },
];
